# Generated by Django 4.1.9 on 2023-06-24 21:40

import acarreapp.carriers.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Vehicle",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "type",
                    models.CharField(
                        choices=[("camioneta", "Camioneta"), ("furgon", "Furgon"), ("camion", "Camion")], max_length=9
                    ),
                ),
                ("brand", models.CharField(max_length=100)),
                ("model", models.CharField(max_length=30)),
                ("color", models.CharField(max_length=40)),
                ("year", models.SmallIntegerField()),
                ("image", models.ImageField(upload_to=acarreapp.carriers.models.Vehicle.image_path)),
            ],
        ),
        migrations.CreateModel(
            name="Carrier",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("photo", models.ImageField(upload_to=acarreapp.carriers.models.Carrier.photo_path)),
                (
                    "doc_type",
                    models.CharField(
                        choices=[("Cedula de ciudadanía", "Cc"), ("Pasaporte", "Passport")], max_length=20
                    ),
                ),
                ("doc_number", models.IntegerField()),
                ("license_number", models.CharField(max_length=50)),
                (
                    "license_type",
                    models.CharField(
                        choices=[
                            ("Licencia Clase A1", "A1"),
                            ("Licencia Clase A2", "A2"),
                            ("Licencia Clase B1", "B1"),
                            ("Licencia Clase B2", "B2"),
                            ("Licencia Clase B3", "B3"),
                            ("Licencia Clase C1", "C1"),
                            ("Licencia Clase C2", "C2"),
                            ("Licencia Clase C3", "C3"),
                        ],
                        max_length=17,
                    ),
                ),
                ("license_due_date", models.DateField()),
                ("license_file", models.FileField(upload_to=acarreapp.carriers.models.Carrier.license_file_path)),
                (
                    "user",
                    models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
                ),
                (
                    "vehicle",
                    models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to="carriers.vehicle"),
                ),
            ],
        ),
    ]
