# Generated by Django 4.1.9 on 2023-06-24 22:29

import acarreapp.carriers.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0001_initial"),
        ("carriers", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Carry",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("lat_from", models.DecimalField(decimal_places=6, max_digits=9)),
                ("long_from", models.DecimalField(decimal_places=6, max_digits=9)),
                ("lat_to", models.DecimalField(decimal_places=6, max_digits=9)),
                ("long_to", models.DecimalField(decimal_places=6, max_digits=9)),
                ("payment_type", models.CharField(choices=[("BT", "Bank Transfer"), ("CA", "Cash")], max_length=10)),
                ("price_offered_by_client", models.IntegerField()),
                ("price_offered_by_carrier", models.IntegerField()),
                ("check_in_time", models.DateTimeField()),
                ("check_out_time", models.DateTimeField()),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("created", "Created"),
                            ("accepted", "Accepted"),
                            ("canceled", "Canceled by User"),
                            ("rejected", "Rejected"),
                        ],
                        default="created",
                        max_length=10,
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="Client",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        primary_key=True,
                        serialize=False,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                ("photo", models.ImageField(upload_to=acarreapp.carriers.models.Client.photo_path)),
                ("doc_type", models.CharField(max_length=50)),
                ("doc_number", models.IntegerField()),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.AddField(
            model_name="carrier",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="carrier",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name="carrier",
            name="license_type",
            field=models.CharField(
                choices=[
                    ("A1", "Licencia Clase A1"),
                    ("A2", "Licencia Clase A2"),
                    ("B1", "Licencia Clase B1"),
                    ("B2", "Licencia Clase B2"),
                    ("B3", "Licencia Clase B3"),
                    ("C1", "Licencia Clase C1"),
                    ("C2", "Licencia Clase C2"),
                    ("C3", "Licencia Clase C3"),
                ],
                max_length=17,
            ),
        ),
        migrations.CreateModel(
            name="Load",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("furniture_type", models.CharField(max_length=255)),
                ("furniture_quantity", models.IntegerField()),
                ("help_required", models.BooleanField(default=False)),
                ("furniture_load", models.BooleanField(default=False)),
                ("furniture_weight_kg", models.FloatField()),
                ("furniture_weight_m3", models.FloatField()),
                ("furniture_photo", models.ImageField(upload_to=acarreapp.carriers.models.Load.furniture_photo_path)),
                ("carry", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="carriers.carry")),
            ],
        ),
        migrations.AddField(
            model_name="carry",
            name="carrier",
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to="carriers.carrier"),
        ),
        migrations.AddField(
            model_name="carry",
            name="client",
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to="carriers.client"),
        ),
    ]
