# Generated by Django 4.1.9 on 2023-06-28 00:23

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("carriers", "0002_carry_client_carrier_created_at_carrier_updated_at_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="carrier",
            name="doc_type",
            field=models.CharField(choices=[("CC", "Cedula de ciudadanía"), ("PST", "Pasaporte")], max_length=20),
        ),
        migrations.AlterField(
            model_name="client",
            name="doc_type",
            field=models.CharField(choices=[("CC", "Cedula de ciudadanía"), ("PST", "Pasaporte")], max_length=20),
        ),
    ]
