# Generated by Django 4.1.9 on 2023-06-28 04:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("carriers", "0003_alter_carrier_doc_type_alter_client_doc_type"),
    ]

    operations = [
        migrations.AlterField(
            model_name="carry",
            name="carrier",
            field=models.ForeignKey(
                blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to="carriers.carrier"
            ),
        ),
        migrations.AlterField(
            model_name="carry",
            name="check_in_time",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="carry",
            name="check_out_time",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="carry",
            name="client",
            field=models.ForeignKey(
                blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to="carriers.client"
            ),
        ),
        migrations.AlterField(
            model_name="carry",
            name="lat_from",
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True),
        ),
        migrations.AlterField(
            model_name="carry",
            name="lat_to",
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True),
        ),
        migrations.AlterField(
            model_name="carry",
            name="long_from",
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True),
        ),
        migrations.AlterField(
            model_name="carry",
            name="long_to",
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True),
        ),
        migrations.AlterField(
            model_name="carry",
            name="payment_type",
            field=models.CharField(
                blank=True, choices=[("BT", "Bank Transfer"), ("CA", "Cash")], max_length=10, null=True
            ),
        ),
        migrations.AlterField(
            model_name="carry",
            name="price_offered_by_carrier",
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name="carry",
            name="price_offered_by_client",
            field=models.IntegerField(default=0),
        ),
    ]
