# Generated by Django 4.1.9 on 2023-06-29 15:12

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("carriers", "0005_client_phone_alter_client_photo"),
    ]

    operations = [
        migrations.AddField(
            model_name="carrier",
            name="lat_now",
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True),
        ),
        migrations.AddField(
            model_name="carrier",
            name="long_now",
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True),
        ),
    ]
